FROM docker.io/node/node:24.13.0-alpine
RUN apk add --no-cache curl
WORKDIR /usr/src/app
COPY package*.json ./
COPY schedule-conf.json ./
RUN npm install
COPY . .
RUN npm run build
CMD ["npm", "run", "start:prod"]
